CREATE TABLE "links" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"shortcode" varchar(32) NOT NULL,
	"target_url" text NOT NULL,
	"user_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "shortcode_idx" ON "links" USING btree ("shortcode");--> statement-breakpoint
CREATE UNIQUE INDEX "user_id_shortcode_idx" ON "links" USING btree ("user_id","shortcode");